name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with: 
          cache: 'npm'
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.100.0
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/Ruby/2.6.9
            input-cache
          key: ${{ runner.os }}-1
      - name: install gh-pages
        run: yarn global add gh-pages fsh-sushi

      - name: install jekyll
        run: gem install jekyll

      - name: which jekyll
        run: which jekyll

      # Runs a set of commands using the runners shell
      - name: Update Publisher
        run: |
          ./_updatePublisher.sh -y -f
      # Runs a set of commands using the runners shell
      - name: Generate output
        run: |
          ./_genonce.sh
      - name: "Github Pages Deployment"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          gh-pages --dist output -u "Addy Naik <anaik@vibrenthealth.com>"
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
